@baseURL=http://localhost:8001/api/v1/classes
# @baseURL = https://portfolio.darshanv.website/api/v1/user

### Create Class
POST {{baseURL}}
Content-Type: application/json

{
    "data": {
        "name": "Class 1",
        "classCode": "ABCD123",
        "teacherId": 1
    }
}

### Get classes
GET {{baseURL}}

### Get class made by teacher using id
GET {{baseURL}}/teacher/1