@baseURL=http://localhost:8001/api/v1/quiz
# @baseURL = https://portfolio.darshanv.website/api/v1/user

### Create Quiz
POST {{baseURL}}
Content-Type: application/json

{
    "data": {
        
            "title": "Aditya rocksss",
            "classCode": "ABCD123",
            "questions": [
                    {
                        "question": "What is the capital of India?",
                        "options": [ "Delhi", "Mumbai", "Kolkata", "Chennai" ],
                        "answer" : "Delhi"
                    } ,
                    {
                        "question": "What is the capital of India?",
                        "options": [ "Delhi", "Mumbai", "Kolkata", "Chennai" ],
                        "answer" : "Delhi"
                    }
                ]
            
    }
}

### Get Quiz
GET {{baseURL}}/ABCD123

### Get Quiz LEADERBOARD
GET {{baseURL}}/leaderboard/ABCD123

### Delete leaderboard
DELETE {{baseURL}}/leaderboard/ABCD123