@baseURL=http://localhost:8001/api/v1/student
# @baseURL = https://portfolio.darshanv.website/api/v1/user

### Create Student
POST {{baseURL}}
Content-Type: application/json

{
    "data": {
        "name" : "Phaneesh S",
        "email": "student@gmail.com",
        "password": "1234"
    }
}

### get all students
GET {{baseURL}}